import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { NextRequest, NextResponse } from 'next/server';

const DOMAIN_ROOT = process.env.PANEL_DOMAINS_ROOT ?? '/tmp/breachrabbit/domains';
const SITE_ROOT = process.env.PANEL_SITES_ROOT ?? '/tmp/breachrabbit/sites';
const SYSTEM_CHANGES_ALLOWED = process.env.PANEL_ALLOW_SYSTEM_CHANGES === 'true';

const DOMAIN_PATTERN = /^(?:[a-zA-Z0-9-]+\.)+[a-zA-Z]{2,63}$/;

function normalizeDomain(input: string) {
  return input.trim().toLowerCase();
}

export async function POST(request: NextRequest) {
  const body = (await request.json().catch(() => null)) as
    | { domain?: string; createDemoSite?: boolean }
    | null;

  const domain = normalizeDomain(body?.domain ?? '');
  const createDemoSite = body?.createDemoSite !== false;

  if (!domain || !DOMAIN_PATTERN.test(domain)) {
    return NextResponse.json(
      {
        status: 'error',
        message: 'Invalid domain format. Expected value like example.com.'
      },
      { status: 400 }
    );
  }

  const domainConfigPath = join(DOMAIN_ROOT, `${domain}.conf`);
  const sitePath = join(SITE_ROOT, domain);
  const siteIndexPath = join(sitePath, 'index.html');

  const config = `server {
  listen 80;
  server_name ${domain};

  root ${sitePath};
  index index.html;

  location / {
    try_files $uri $uri/ =404;
  }
}
`;

  const demoPage = `<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>${domain}</title>
  </head>
  <body>
    <h1>${domain} is online</h1>
    <p>Generated by BreachRabbit panel domain wizard.</p>
  </body>
</html>
`;

  if (!SYSTEM_CHANGES_ALLOWED) {
    return NextResponse.json({
      status: 'dry-run',
      message:
        'System actions are disabled. Set PANEL_ALLOW_SYSTEM_CHANGES=true to create domain files.',
      domain,
      files: createDemoSite ? [domainConfigPath, siteIndexPath] : [domainConfigPath]
    });
  }

  await mkdir(DOMAIN_ROOT, { recursive: true });
  await writeFile(domainConfigPath, config, 'utf8');

  const files = [domainConfigPath];

  if (createDemoSite) {
    await mkdir(sitePath, { recursive: true });
    await writeFile(siteIndexPath, demoPage, 'utf8');
    files.push(siteIndexPath);
  }

  return NextResponse.json({
    status: 'ok',
    message: createDemoSite
      ? 'Domain and demo site created successfully.'
      : 'Domain config created successfully.',
    domain,
    files
  });
}
